#!/usr/bin/env bash

fe() {
    local selected
    selected="$(fd . "$@" --follow --hidden --type file | fzf --reverse)"
    if [ -n "$selected" ]; then
        $EDITOR "$selected"
    fi
}

fcd() {
    local selected
    selected="$(
        fd . "$@" --follow --hidden --type dir --exclude ".git" | fzf --reverse
    )"
    [ -n "$selected" ] && cd "$selected" || return
}

yazi_wrapper() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    IFS= read -r -d '' cwd <"$tmp"
    [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
    rm -f -- "$tmp"
}

export LESS_TERMCAP_md=$'\E[1;33m'      # begin bold
export LESS_TERMCAP_so=$'\E[01;44;33m'  # begin standout
export LESS_TERMCAP_mb=$'\E[1;31m'      # begin blinking
export LESS_TERMCAP_us=$'\E[1;32m'      # begin underline
export LESS_TERMCAP_se=$'\E[0m'         # end standout
export LESS_TERMCAP_me=$'\E[0m'         # end mode
export LESS_TERMCAP_ue=$'\E[0m'         # end underline

man() {
    env \
    LESS=R \
    GROFF_NO_SGR=0 \
    MANPAGER="less -R" \
    LC_CTYPE=en_US.UTF-8 \
    man "$@"
}

tfont() {
    echo "Normal Text"
    echo -e "\e[1mBold Text\e[0m"
    echo -e "\e[3mItalic Text\e[0m"
    echo -e "\e[3m\e[1mBold & Italic Text\e[0m"
    echo -e "\e[4mUnderline Text\e[0m"
    echo -e "\e[9mStrikethrough Text\e[0m"
    echo -e "\e[31mRed Text\e[0m"
    echo -e "\x1B[31mError? Text\e[0m"
    echo "== === !== >= <= =>"
    echo "契          勒 鈴 "
}
